version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-world-uchiyama"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xm51tcnxor4h"
s3_prefix = "sam-hello-world-uchiyama"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
